### ISSUE TITLE
Feature/Runner Not generating if under folder hierarchy

### ISSUE THREAD

**Issue by ManjunathPrabhakar** [trivago/cucable-plugin#164] opened 2020-07-06 07:09 UTC
Hi , i have a requirement where my feature files are arranged in different folders depending on it functionality. PFB
![image](https://user-images.githubusercontent.com/10891658/86565175-fbd74980-bf84-11ea-9430-a0d19138a246.png)

In the image, i want to execute feature files under folder Associates. (Idea here is my *.Feature file can be under any folder/root inside Features Folder). Cucable is expected to access it while i just give the below in my Maven POM.
`<sourceFeatures>src/test/Features</sourceFeatures>`

But, when i have a feature file either in root or 2-3 folders under, it works fine. But when i have multiple folders and hierarchy cucable fails to execute

_`Failed to execute goal com.trivago.rta:cucable-plugin:1.7.2:parallel (generate-test-resources) on project SP: Execution generate-test-resources of goal com.trivago.rta:cucable-plugin:1.7.2:parallel failed.`_

**Comment by ManjunathPrabhakar** [comment] 2020-07-06 07:13
@laxersaz Please Advise

**Comment by laxersaz** [comment] 2020-07-08 10:13
Sorry, I don't really understand the problem. On the one hand you said that it works fine under the root folder or subfolders but on the other hand you said that it doesn't work with a multi-folder hierarchy. Please either specify the exact repro steps or attach an example project.

**Comment by ManjunathPrabhakar** [comment] 2020-07-10 06:41
@laxersaz : Okay, considering the screenshot i have uploaded above. 
i have specified my features directory in pom as `<sourceFeatures>src/test/Features</sourceFeatures>`
And in project structure my features are located under & within multiple folder. (refer the left side of screenshot). 
And when i have to execute the project i get the error.

meanwhile if you need more clarity, I'll reproduce the same in a sample project share here

**Comment by laxersaz** [comment] 2020-07-10 08:08
You didn't have to close this issue. 
Ah I understand what you meant now. I will check this behavior.
Could you try to run the project with Maven's `-X` switch to see the full output?

**Comment by laxersaz** [comment] 2020-08-15 14:16
I could not reproduce this behavior at all. Please attach a sample project to reproduce it.

**Closed** 2020-08-15 14:18 UTC
Labels: question

**Comment by laxersaz** [comment] 2020-08-24 06:49
You too 😃
